### PR TITLE
Fixed broken link for "set up a discussion forum"

### PR DESCRIPTION
**Pull request by jasonclemons**

### CODE REVIEW

**Comment by franzliedke** [comment]
I am confused. This works perfectly for me on [this page](http://flarum.org/docs/).

**Comment by franzliedke** [comment]
Also, we use this syntax all over the place in the docs - or am I missing something?

**Comment by jasonclemons** [comment]
My mistake, I was reading it directly from the repo and not thinking that it's using Jekyll to parse the links. It's broken on the repo view, but not on the site.

I'll go ahead and close this :D

**Comment by dcsjapan** [comment]
Please forgive my thumbs-up on the first post; I'm running a bit of a fever & didn't check it carefully.

A+ for making an effort to improve the docs, in any case. 😄

**Pull request closed without merging**
