### PR TITLE
Update common-issues.md

### PR DESCRIPTION
**Pull request by ykangoakridge**
add debug tips for flarum avatar upload error

### CODE REVIEW

**Comment by tobyzerner** [comment]
@ykangoakridge any reason why you closed this?

**Comment by ykangoakridge** [comment]
not really, i just want to add some tips on the doc for uploading avatars. but i’m not familiar with github operations, so might be mis-operations. feel free to revoke any mistakes i might caused.


-Yong


On Dec 21, 2017, at 5:56 PM, Toby Zerner <notifications@github.com<mailto:notifications@github.com>> wrote:


@ykangoakridge<https://github.com/ykangoakridge> any reason why you closed this?

**Comment by gwillem** [comment]
@ykangoakridge it looks perfectly valid? Thanks for your contribution, and please reopen :)

**Comment by franzliedke** [comment]
@ykangoakridge I am afraid you need to rebase this on the latest master to fix the conflicts.

**Comment by franzliedke** [comment]
I am closing this issue as it seems to have grown stale.

**Pull request closed without merging**
