### PR TITLE
Add FAQ for issue/milestone queries

### PR DESCRIPTION
**Pull request by dcsjapan**
- Adds one item to the FAQ
- Not tested locally; please check before merging

### CODE REVIEW

**Comment by franzliedke** [comment]
Looking good, thanks!

**Comment by franzliedke** [comment]
Just had to fix the [contributing link](https://github.com/flarum/flarum.github.io/commit/295fe4ebb99adb4ffc1e300aae39545590e3773e).

**Comment by dcsjapan** [comment]
Thanks ... sorry about the link, I thought I was pasting the right URL ... :sweat_smile:

**Comment by dcsjapan** [comment]
@franzliedke Come to think of it, perhaps that particular link should point to the following instead:

https://github.com/flarum/flarum/blob/master/CONTRIBUTING.md

The present link (which was the one I was aiming for too) is mostly about bug reporting.

**Comment by franzliedke** [comment]
Yeah, I was thinking about that, too. For now, I think, the former one is safer to be always there, though...

**Comment by dcsjapan** [comment]
Okay, we'll hope people follow the links.

In the future, it might be best to put that blob into the docs site as "Contributing" and rename the current "Contributing" page to "Reporting Bugs" or something. I'll make a note of it.

**Pull request merged**
