### PR TITLE
Update installation.md

### PR DESCRIPTION
**Pull request by punitm0**

### CODE REVIEW

**Comment by dsevillamartin** [comment]
The new, updated documentation is at https://github.com/flarum/docs, you may want to check there.

**Comment by franzliedke** [comment]
@Arkinn What do you say? Do we want this here or in the flarum/docs repo?

**Comment by Arkinn** [comment]
@franzliedke I'd prefer it to remain in the flarum/docs repo, keep everything together then.

**Comment by franzliedke** [comment]
Okay, in that case... @punit2502 Could you re-submit this pull request to https://github.com/flarum/docs, please? :smiley:

**Comment by franzliedke** [comment]
Stale and obsolete, the text has already been removed.

@Arkinn As has been practice for the last few weeks (months?), we will accept contributions into this repo, so that they go live quickly. We will have to merge the contents of the old and new documentation once the new site (integrating the docs repo) goes live.

**Pull request closed without merging**
