### PR TITLE
Fix grammar in line 179

### PR DESCRIPTION
**Pull request by dcsjapan**
Fixes a small grammatical error I just ran across.

### CODE REVIEW

**Comment by tobyzerner** [comment]
Hmm it should actually be "its content is executed" I think? "Are" sounds odd, because the file doesn't haven't multiple contents...

**Comment by dcsjapan** [comment]
As for that, you'd know better than me. I just thought the subject and verb ought to agree.

**Comment by tobyzerner** [comment]
Thanks!

**Comment by dcsjapan** [comment]
Sure thing. (I'm just trying to get some of these Stickies off my screen before the new MBP gets here, so I'll be ready for the big installation and updating binge.)

**Comment by tobyzerner** [comment]
So exciting! :D

**Pull request merged**
