### PR TITLE
Add missing `curl` PHP extension in installation documentation.

### PR DESCRIPTION
**Pull request by Lavode**
Also list required extensions alphabetically, making it easier to check
whether all are installed.

### CODE REVIEW

**Comment by franzliedke** [comment]
Hmm, `curl` is not listed as one of our required extensions [in the installer code](https://github.com/flarum/core/blob/043aa0f2d964b33e00e6b0c4d0d0ff88ee973745/src/Install/InstallServiceProvider.php#L35-L43).

Is this a requirement for running Composer?

**Comment by Lavode** [comment]
Nah, one of your dependencies seems to depend on it.

Eg below failure happens during the build of a Debian 9-based docker image for flarum, if the `curl` extension isn't installed.
```
Step 10/17 : RUN COMPOSER_HOME=/tmp/composer composer create-project flarum/flarum /opt/flarum v0.1.0-beta.7 --stability=beta
 ---> Running in 1564c74db29f
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Installing flarum/flarum (v0.1.0-beta.7)
  - Installing flarum/flarum (v0.1.0-beta.7)
    Downloading: 100%         

Created project in /opt/flarum
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - flarum/flarum-ext-akismet v0.1.0-beta.3 requires tijsverkoyen/akismet ^1.1 -> satisfiable by tijsverkoyen/akismet[1.1.0, 1.1.1].
    - flarum/flarum-ext-akismet v0.1.0-beta.5 requires tijsverkoyen/akismet ^1.1 -> satisfiable by tijsverkoyen/akismet[1.1.0, 1.1.1].
    - flarum/flarum-ext-akismet v0.1.0-beta.6 requires tijsverkoyen/akismet ^1.1 -> satisfiable by tijsverkoyen/akismet[1.1.0, 1.1.1].
    - tijsverkoyen/akismet 1.1.1 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - tijsverkoyen/akismet 1.1.0 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - Installation request for flarum/flarum-ext-akismet ^0.1.0 -> satisfiable by flarum/flarum-ext-akismet[v0.1.0-beta.3, v0.1.0-beta.5, v0.1.0-beta.6].
```

**Comment by franzliedke** [comment]
Ah, that's not a core dependency, though, but one of the extensions (which is bundled with our default install, but not a "requirement").

@flarum/core Hmm, how do we want to handle this?

**Comment by gwillem** [comment]
Either unbundle, or add curl as req? I vote for unbundle, not many people
seem to use it (based on FreeFlarum usage stats).

**Comment by tobyzerner** [comment]
Unbundle!

**Comment by franzliedke** [comment]
The alternative would be to show a screen upon installation that lets you choose which extensions you want to install, and adjust the requirements accordingly.

**Comment by luceos** [comment]
@gwillem can you share the exact percentage based on forums that are active for over a month? I think that might give us a better interpretation. 

@flarum/core I agree with Toby let's unbundle for now. Let's look at a better solution on the long run.

**Comment by gwillem** [comment]
akismet: 59 out of 1300 installs (haven't checked whether they are live or
not)

**Comment by franzliedke** [comment]
Unbundling means removing from the flarum/flarum skeleton, right? Okay if I do this?

**Comment by luceos** [comment]
@franzliedke 👍 go ahead

**Pull request closed without merging**
